delivery 2

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -9,20 +9,20 @@ jobs:
     - uses: actions/checkout@v3
     - name: check
       run: |
-      files=$(find . -lname "*.o")
-      files+=$(find . -lname "*.a")
-      files+=$(find . -lname "*.so")
-      files+=$(find . -lname "*.gcno")
-      files+=$(find . -lname "*.gcda")
-      files+=$(find . -lname "*.gcovr")
-      files+=$(find . -lname "#*")
-      files+=$(find . -lname "*-")
-      files+=$(find . -lname "pain au chocolat")
-      dir=$(find . -type d -name "tmp")
-      if [ $lines -ne 0 ] && [ $dir -ne 0 ]; then
-        echo "::error::Unwanted files detected: $lines"
-        exit 1
-      fi
+        files=$(find . -lname "*.o")
+        files+=$(find . -lname "*.a")
+        files+=$(find . -lname "*.so")
+        files+=$(find . -lname "*.gcno")
+        files+=$(find . -lname "*.gcda")
+        files+=$(find . -lname "*.gcovr")
+        files+=$(find . -lname "#*")
+        files+=$(find . -lname "*-")
+        files+=$(find . -lname "pain au chocolat")
+        dir=$(find . -type d -name "tmp")
+        if [ $lines -ne 0 ] && [ $dir -ne 0 ]; then
+          echo "::error::Unwanted files detected: $lines"
+          exit 1
+        fi
   check_program_compilation:
     runs-on: ubuntu-latest
     steps:
